DELETE  http://103.218.159.211:9200/members
###
PUT http://103.218.159.211:9200/members
Content-Type: Application/json

{
  "settings": {
    "number_of_shards": 5,
    "number_of_replicas": 1,
    "analysis": {
      "tokenizer": {
        "member_name_ngram_tokenizer": {
          "type": "ngram",
          "min_gram": 2,
          "max_gram": 3,
          "token_chars": "letter"
        },
        "member_name_nori_tokenizer": {
          "type": "nori_tokenizer"
        }
      },
      "analyzer": {
        "member_name_search_analyzer": {
          "type": "custom",
          "tokenizer": "member_name_ngram_tokenizer"
        },
        "member_name_nori_analyzer": {
          "type": "custom",
          "tokenizer": "member_name_nori_tokenizer"
        }
      }
    }
  },
  "mappings": {
      "properties": {
        "id": { "type": "long"},
        "nickname": { "type": "keyword"},
        "name": {
          "type": "text",
          "analyzer": "member_name_search_analyzer",
          "search_analyzer": "member_name_nori_analyzer"},
        "phone": {"type": "keyword"},
        "login_id": { "type": "text"},
        "birth_year": { "type": "integer"},
        "birth_month": { "type": "integer"},
        "birth_day": { "type": "integer"},
        "email": { "type": "keyword"},
        "sign_up_date": { "type": "date"},
        "withdrawal_date": {
          "type": "date",
          "null_value": true },
        "is_withdrawal": { "type": "boolean"},
        "is_blocked": { "type": "boolean"},
        "point": { "type": "long"},
        "member_grade_id": { "type": "keyword"},
        "gender_code": { "type": "keyword"}
      }
    }
}

###

POST http://103.218.159.211:9200/members/_search
Content-Type: Application/json

{
  "query": {
    "match": {
      "id": 1
    }
  }
}

###

GET localhost:9200/members/_mapping?pretty=true

###

GET localhost:9200/members/_search?q=name:선홍

###

