spring:
  application:
    name: yesaladin-shop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.151.141:3306/yesaladin_shop_dev?serverTimezone=Asia/Seoul
    username: yesaladin
    password: PR7QyDl]Ojwaw7Y@

  jpa:
    hibernate:
      ddl-auto: none
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: 133.186.241.187:9092,133.186.223.175:9092,133.186.241.4:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      properties:
        spring:
          json:
            value:
              default:
                type: java.util.HashMap
        partition:
          assignment:
            strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor

management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: health, prometheus
      base-path: /monitor
      path-mapping:
        health: /l7check
log:
  logncrash:
    app-key: h98AoVSn5I3rIctz

coupon:
  topic:
    user-download: user_download_coupon_dev
    auto-issuance: auto_issuance_coupon_dev
    give-request: dev_yesaladin_coupon_give_request
    give-request-limit: dev_yesaladin_coupon_give_request_limit
    given: dev_yesaladin_coupon_given
    give-request-cancel: dev_yesaladin_coupon_give_request_cancel
    use-request: dev_yesaladin_coupon_use_request
    used: dev_yesaladin_coupon_used
    use-request-cancel: dev_yesaladin_coupon_use_request_cancel
    give-request-response: dev_yesaladin_coupon_give_request_response
    use-request-response: dev_yesaladin_coupon_use_request_response

elastic:
  host: 103.218.159.211:9200

yesaladin:
  gateway:
    base: http://localhost:8072
    auth: http://localhost:8072/auth
    coupon: http://localhost:8072/coupon

# 테스트용 스토리지
storage-token:
  auth-url: https://api-identity.infrastructure.cloud.toast.com/v2.0/tokens
  storage-url: https://api-storage.cloud.toast.com/v1
  tenant-id: fcb81f74e379456b8ca0e091d351a7af
  storage-account: AUTH_fcb81f74e379456b8ca0e091d351a7af
  container-name: yesaladinTest
  username: tidh1640@naver.com
  password: yesaladin