#spring:
#  application:
#    name: yesaladin-shop
#  config:
#    import: configserver:http://133.186.209.185:8888

spring:
  application:
    name: yesaladin-shop
  profiles:
    active: prod
  config:
    import: optional:configserver:http://192.168.0.78:8888
