spring:
  application:
    name: yesaladin-shop
  datasource:
    url: jdbc:h2:mem:/test
    username: sa
    password:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

elastic:
  host: 103.218.159.211:9200

storage-token:
  auth-url: https://api-identity.infrastructure.cloud.toast.com/v2.0/tokens
  storage-url: https://api-storage.cloud.toast.com/v1
  tenant-id: fcb81f74e379456b8ca0e091d351a7af
  storage-account: AUTH_fcb81f74e379456b8ca0e091d351a7af
  container-name: yesaladinTest
  username: tidh1640@naver.com
  password: yesaladin
  thumbnail-path: product/thumbnail

logging:
  level:
    tracer: TRACE

yesaladin:
  coupon:
    url: http://localhost:8085
  gateway:
    base: http://localhost:8072
    auth: http://localhost:8072